import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}


const veiculosKK = [
  "10F",
  "10F Widebody",
  "300R",
  "811",
  "8F Drafter",
  "9F",
  "9F Cabrio",
  "Adder",
  "Akuma",
  "Alpha",
  "Apocalypse Deathbike",
  "Apocalypse Slamvan",
  "Ariant",
  "Asbo",
  "Asea",
  "Asterope",
  "Astron",
  "Aurora Sport",
  "Autarch",
  "Avarus",
  "Bagger",
  "Baller",
  "Baller Blindada",
  "Baller II",
  "Baller LE",
  "Baller LE LWB",
  "Baller ST",
  "Banshee",
  "Banshee 900R",
  "Bati 701",
  "Bati 801",
  "Bati Patrocínio",
  "BeeJay XL",
  "Benefactor  Br8",
  "Benson",
  "Benson 2",
  "Bestia GTS",
  "BF 400",
  "Biff",
  "Bifta",
  "Bison",
  "Bison STX",
  "Blade",
  "Blazer",
  "Blazer Hotrod",
  "Blista",
  "Blista Compact",
  "Blista Go Go Monkey",
  "Blista Kanjo",
  "BMX (Saltos)",
  "BMX Custom",
  "Bobcat XL",
  "Bodhi",
  "Boor",
  "Boxville GoPostal",
  "Boxville Humane",
  "Boxville LSDWP",
  "Boxville PostOp",
  "Brawler",
  "Brigham",
  "Brioso 300",
  "Brioso 300 Widebody",
  "Brioso Off-Road",
  "Brioso R/A",
  "Broadway",
  "Brutus",
  "Buccaneer",
  "Buccaneer Custom",
  "Buffalo",
  "Buffalo EVX",
  "Buffalo HellHound",
  "Buffalo Patrocinio",
  "Buffalo S",
  "Buffalo STX",
  "Bullet",
  "Burguer Shot Stallion",
  "Burrito",
  "Burrito 2",
  "Burrito 3",
  "Burrito 4",
  "Burrito The Lost MC",
  "Caddy",
  "Caddy 2",
  "Caddy 3",
  "Calico GTF",
  "Callista",
  "Camper",
  "Caracara 4x4",
  "Carbon RS",
  "Carbonizzare",
  "Casco",
  "Cavalcade",
  "Cavalcade II",
  "Cavalcade XL CTX",
  "Champion",
  "Cheburek",
  "Cheetah",
  "Cheetah Classic",
  "Chimera",
  "Chino",
  "Chino Custom",
  "Cinquemila",
  "Cliffhanger",
  "Clique",
  "Clique Wagon",
  "Club",
  "Cognoscenti",
  "Cognoscenti 55",
  "Cognoscenti Blindado",
  "Cognoscenti Cabrio",
  "Comet",
  "Comet Retro",
  "Comet S2",
  "Comet S2 Cabrio",
  "Comet S2 Cabrio CTX",
  "Comet S2 CTX",
  "Comet Safari",
  "Comet SR",
  "Contender",
  "Coquette",
  "Coquette BlackFin",
  "Coquette Classic",
  "Coquette D10",
  "Coquette Vice",
  "Coquette Vice Cabrio",
  "Corsita",
  "Cortador de grama",
  "Coyote",
  "Cruiser (Antiga)",
  "Cyclone",
  "Cypher",
  "Daemon Custom",
  "Dashound",
  "Declasse Dr1",
  "Defiler",
  "Deimos",
  "Deity",
  "Deluxo Retro",
  "Deveste",
  "Deviant",
  "Diablous",
  "Diablous Custom",
  "Dilettante",
  "Dominator",
  "Dominator ASP",
  "Dominator GTX",
  "Dominator Patrocinio",
  "Domitanor GTT",
  "Double T",
  "Draugur",
  "Drift Tampa",
  "Dubsta",
  "Dubsta 22",
  "Dubsta 6X6",
  "Dubsta II",
  "Dukes",
  "Dukes Beater",
  "Dyna King",
  "Dynasty",
  "Elegy Retro",
  "Elegy RH5",
  "Elegy RH6",
  "Elegy RH7",
  "Elegy RH8",
  "Elegy RH8 CTX",
  "Elegy RH9",
  "Elegy RHX",
  "Ellie",
  "Emerus",
  "Emperor",
  "Empilhadeira",
  "Endurex (Triathlon)",
  "Enduro",
  "Entity MT",
  "Entity XF",
  "Entity XXR",
  "Escavadeira",
  "Esperta",
  "Esskey",
  "ETR1",
  "Eudora",
  "Eudora Custom",
  "Euros",
  "Euros Classic",
  "Everon",
  "Exemplar",
  "F340 R",
  "F440 R",
  "F620",
  "Faction",
  "Faction Custom",
  "Faction Custom Donk",
  "Fagaloa",
  "Faggio",
  "Faggio Modified",
  "Faggio Sport",
  "FatBoy",
  "FatBoy 21",
  "FCR 1000",
  "FCR 1000 Custom",
  "Felon",
  "Felon GT",
  "Feltzer",
  "Fieldmaster",
  "Fixter (Corrida)",
  "Flash GT",
  "FMJ",
  "Food Truck",
  "FQ 2",
  "Fränken Stange",
  "Fugitive",
  "Furia",
  "Furore GT",
  "Furzen",
  "Fusilade",
  "Futo",
  "Futo GTX",
  "Gang Burrito",
  "Gargoyle",
  "Gauntlet",
  "Gauntlet Classic",
  "Gauntlet Classic Custom",
  "Gauntlet Hellfire",
  "Gauntlet S",
  "Gauntlet Turbo",
  "GB 200",
  "Glendale",
  "Glendale Custom",
  "GP1",
  "Granger",
  "Granger 3600LX",
  "Greenwood",
  "Gresley",
  "Growler",
  "GT 500",
  "Guardian",
  "Habanero",
  "Hakuchou",
  "Hakuchou Drag",
  "Hauler",
  "Hellion",
  "Hermes",
  "Hexer",
  "Hotknife",
  "Hotring",
  "Hotring Everon",
  "Hotring Hellfire",
  "Huntley S",
  "Hustler",
  "I-Wagen",
  "Ignus",
  "Imorgon",
  "Impaler",
  "Inductor",
  "Infernus",
  "Infernus Classic",
  "Ingot",
  "Innovation",
  "Intruder",
  "Issi",
  "Issi Classic",
  "Issi Rally",
  "Issi Sport",
  "Itali GTB",
  "Itali GTB Custom",
  "Itali GTO",
  "Itali GTO Stinger TT",
  "Itali RSX",
  "Jackal",
  "JB 700",
  "Jester",
  "Jester Classic",
  "Jester Custom",
  "Jester Patrocinio",
  "Jester RR",
  "Journey II",
  "Jubilee",
  "Jugular",
  "Junk Energy Inductor",
  "Kalahari",
  "Kamacho",
  "Kampfer",
  "Kanjo SJ",
  "Kawaii",
  "Khamelion",
  "Komoda",
  "Krieger",
  "Kuruma",
  "La Coureuse",
  "Landstalker",
  "Landstalker XL",
  "Lectro",
  "Liberator",
  "LM87",
  "Locust",
  "Lost Slamvan",
  "Lynx",
  "Mamba",
  "Manana",
  "Manana Custom",
  "Manchez",
  "Manchez Scout",
  "Manchez Scout C",
  "Marshall",
  "Massacro",
  "Massacro Patrocinio",
  "Mesa",
  "Mesa Offroad",
  "Michelli",
  "Minivan",
  "Minivan Custom",
  "Monroe",
  "MonstroCiti",
  "Moonbeam",
  "Moonbeam Custom",
  "Mule",
  "Mule Custom",
  "Mule Heist",
  "Mule Ramp-Door",
  "Nebula",
  "Nemesis",
  "Neo",
  "Neon",
  "Nero",
  "Nero Custom",
  "Nexus",
  "Nightblade",
  "Nightblade Classic",
  "Nightshade",
  "Novak",
  "Ocelot R88",
  "Omnis",
  "Omnis e-GT",
  "Ônibus",
  "Ônibus do Aeroporto",
  "Oracle",
  "Oracle XS",
  "Osiris",
  "Outlaw",
  "Packer",
  "Panthere",
  "Panto",
  "Paradise",
  "Paragon R",
  "Paragon R Blindado",
  "Pariah",
  "Patriot",
  "Patriot Mil-Spec",
  "Patriot Stretch",
  "PCJ 600",
  "Penetrator",
  "Penumbra",
  "Penumbra FF",
  "Penumbra Retro",
  "Penumbra Retro Cabrio",
  "Penumbra Retro Widebody",
  "Penumbra Retro Widebody Cabrio",
  "Peyote",
  "Peyote Custom",
  "Peyote Gasser",
  "Phantom",
  "Phantom Custom",
  "Phoenix",
  "Picador",
  "Pigalle",
  "Pony",
  "Pororoca",
  "Postlude",
  "Pounder",
  "Powersurge",
  "Prairie",
  "Premier",
  "Previon",
  "Primo",
  "Primo Custom",
  "Progen Pr4",
  "Radius",
  "Raiden",
  "Rallytruck",
  "Rampant Rocket",
  "Rancher XL",
  "Rapid GT",
  "Rapid GT Cabrio",
  "Rapid GT3",
  "Raptor",
  "Rat-Truck",
  "Ratel",
  "RE-7B",
  "Reaper",
  "Rebel",
  "Rebla GTS",
  "Redwood Gauntlet",
  "Reever",
  "Regina",
  "Remus",
  "Remus II",
  "Retinue",
  "Retinue MK II",
  "Revolter",
  "Rhapsody",
  "Rhinehart",
  "Rhinehart M",
  "Riata",
  "Riata TX",
  "Rocoto",
  "Roosevelt",
  "Roosevelt Valor",
  "Roxanne",
  "RT3000",
  "Ruffian",
  "Ruiner",
  "Ruiner ZZ-8",
  "Rumpo Off-road",
  "Ruston",
  "S230",
  "S80RR",
  "S95 CTX",
  "Sabre Turbo",
  "Sabre Turbo Custom",
  "Sadler",
  "Sanchez",
  "Sanchez Patrocínio",
  "Sanctus",
  "Sandking",
  "Sandking XL",
  "Savestra",
  "SC1",
  "Schafter",
  "Schafter LWB",
  "Schafter V12",
  "Schafter V12 (Blindado)",
  "Schlagen GT",
  "Schneider STR",
  "Schwartzer",
  "Scorcher (Trilha)",
  "Scrap Truck",
  "Seminole",
  "Seminole Frontier",
  "Sentinel",
  "Sentinel Classic",
  "Sentinel Classic Widebody",
  "Sentinel SG4",
  "Sentinel XS",
  "Serrano",
  "Seven 70",
  "Sheava S",
  "Slamtruck",
  "Slamvan",
  "Slamvan Custom",
  "Slave",
  "SM722",
  "Sovereign",
  "Specter",
  "Specter Custom",
  "Speedo",
  "Speedo Express",
  "Stafford",
  "Stallion",
  "Stanier",
  "Stinger",
  "Stinger GT",
  "Stirling GT",
  "Stratum",
  "Street Blazer",
  "Streiter",
  "Stretch",
  "Stryder",
  "Sugoi",
  "Sultan",
  "Sultan Classic",
  "Sultan RS",
  "Sultan RS Classic",
  "Sultan RSX",
  "Sunrise R",
  "Super Diamond",
  "Surano",
  "Surfer",
  "Surfer Custom",
  "Surge",
  "Swinger",
  "T20",
  "Tahoma Coupe",
  "Tailgater",
  "Tailgater S",
  "Taipan",
  "Tampa",
  "Tempesta",
  "Tempesta Custom",
  "Templar",
  "TerrorByte",
  "Tezeract",
  "The Lost Daemon",
  "Thrax",
  "Thrust",
  "Tigon",
  "Tipper",
  "Tipper 2",
  "Titan",
  "Titan Low",
  "Titan T",
  "Torero",
  "Torero XO",
  "Tornado",
  "Tornado Custom",
  "Tornado Soft Top",
  "Toros",
  "Tour Bus",
  "Trash Truck",
  "Tri-cycles (Triathlon)",
  "Trophy Truck",
  "Trophy Truck Limited",
  "Tropos",
  "Tulip",
  "Tulip M100",
  "Turismo",
  "Turismo Classic",
  "Turismo S",
  "Tyrant",
  "Tyrus",
  "Utility Truck",
  "Utility Truck Contender",
  "V-STR",
  "Vacca",
  "Vader",
  "Vagner",
  "Vagrant",
  "Vamos",
  "Vectre",
  "Velox",
  "Verlierer",
  "Verus",
  "Vigero",
  "Vigero Rumbler",
  "Vigero VL1",
  "Vigero ZX",
  "Vindicator",
  "Virgo",
  "Virgo Classic",
  "Virgo Classic Custom",
  "Virtue",
  "Viseris",
  "Visione",
  "Voltic",
  "Voodoo Custom",
  "Vortex",
  "Vulture",
  "Walton L35",
  "Warrener",
  "Warrener HKR",
  "Washington",
  "Weevil",
  "Weevil Custom",
  "Whippet (Triathlon)",
  "Windsor",
  "Windsor Drop",
  "Winky",
  "Wintergreen",
  "Wolfsbane",
  "X80 Prototype",
  "XA-21",
  "XLS",
  "XLS Blindada",
  "Yosemite",
  "Yosemite Drift",
  "Yosemite Rancher",
  "Youga",
  "Youga Classic",
  "Youga Classic 4x4",
  "Z 190",
  "Z-Type",
  "Zeno",
  "Zentorno",
  "Zion",
  "Zion Cabrio",
  "Zion Classic",
  "Zion Classic CTX",
  "Zombie Bobber",
  "Zombie Chopper",
  "Zorrusso",
  "ZR Classic",
  "ZR-380 S",
  "ZR-390",
  "ZR250",
  "ZR350",
  "ZR350 Custom"
];
