import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
export const veiculosKK = [
  { id: 1, nome: "10F" },
  { id: 2, nome: "10F Widebody" },
  { id: 3, nome: "300R" },
  { id: 4, nome: "811" },
  { id: 5, nome: "8F Drafter" },
  { id: 6, nome: "9F" },
  { id: 7, nome: "9F Cabrio" },
  { id: 8, nome: "Adder" },
  { id: 9, nome: "Akuma" },
  { id: 10, nome: "Alpha" },
  { id: 11, nome: "Apocalypse Deathbike" },
  { id: 12, nome: "Apocalypse Slamvan" },
  { id: 13, nome: "Ariant" },
  { id: 14, nome: "Asbo" },
  { id: 15, nome: "Asea" },
  { id: 16, nome: "Asterope" },
  { id: 17, nome: "Astron" },
  { id: 18, nome: "Aurora Sport" },
  { id: 19, nome: "Autarch" },
  { id: 20, nome: "Avarus" },
  { id: 21, nome: "Bagger" },
  { id: 22, nome: "Baller" },
  { id: 23, nome: "Baller Blindada" },
  { id: 24, nome: "Baller II" },
  { id: 25, nome: "Baller LE" },
  { id: 26, nome: "Baller LE LWB" },
  { id: 27, nome: "Baller ST" },
  { id: 28, nome: "Banshee" },
  { id: 29, nome: "Banshee 900R" },
  { id: 30, nome: "Bati 701" },
  { id: 31, nome: "Bati 801" },
  { id: 32, nome: "Bati Patrocínio" },
  { id: 33, nome: "BeeJay XL" },
  { id: 34, nome: "Benefactor Br8" },
  { id: 35, nome: "Benson" },
  { id: 36, nome: "Benson 2" },
  { id: 37, nome: "Bestia GTS" },
  { id: 38, nome: "BF 400" },
  { id: 39, nome: "Biff" },
  { id: 40, nome: "Bifta" },
  { id: 41, nome: "Bison" },
  { id: 42, nome: "Bison STX" },
  { id: 43, nome: "Blade" },
  { id: 44, nome: "Blazer" },
  { id: 45, nome: "Blazer Hotrod" },
  { id: 46, nome: "Blista" },
  { id: 47, nome: "Blista Compact" },
  { id: 48, nome: "Blista Go Go Monkey" },
  { id: 49, nome: "Blista Kanjo" },
  { id: 50, nome: "BMX (Saltos)" },
  { id: 51, nome: "BMX Custom" },
  { id: 52, nome: "Bobcat XL" },
  { id: 53, nome: "Bodhi" },
  { id: 54, nome: "Boor" },
  { id: 55, nome: "Boxville GoPostal" },
  { id: 56, nome: "Boxville Humane" },
  { id: 57, nome: "Boxville LSDWP" },
  { id: 58, nome: "Boxville PostOp" },
  { id: 59, nome: "Brawler" },
  { id: 60, nome: "Brigham" },
  { id: 61, nome: "Brioso 300" },
  { id: 62, nome: "Brioso 300 Widebody" },
  { id: 63, nome: "Brioso Off-Road" },
  { id: 64, nome: "Brioso R/A" },
  { id: 65, nome: "Broadway" },
  { id: 66, nome: "Brutus" },
  { id: 67, nome: "Buccaneer" },
  { id: 68, nome: "Buccaneer Custom" },
  { id: 69, nome: "Buffalo" },
  { id: 70, nome: "Buffalo EVX" },
  { id: 71, nome: "Buffalo HellHound" },
  { id: 72, nome: "Buffalo Patrocinio" },
  { id: 73, nome: "Buffalo S" },
  { id: 74, nome: "Buffalo STX" },
  { id: 75, nome: "Bullet" },
  { id: 76, nome: "Burguer Shot Stallion" },
  { id: 77, nome: "Burrito" },
  { id: 78, nome: "Burrito 2" },
  { id: 79, nome: "Burrito 3" },
  { id: 80, nome: "Burrito 4" },
  { id: 81, nome: "Burrito The Lost MC" },
  { id: 82, nome: "Caddy" },
  { id: 83, nome: "Caddy 2" },
  { id: 84, nome: "Caddy 3" },
  { id: 85, nome: "Calico GTF" },
  { id: 86, nome: "Callista" },
  { id: 87, nome: "Camper" },
  { id: 88, nome: "Caracara 4x4" },
  { id: 89, nome: "Carbon RS" },
  { id: 90, nome: "Carbonizzare" },
  { id: 91, nome: "Casco" },
  { id: 92, nome: "Cavalcade" },
  { id: 93, nome: "Cavalcade II" },
  { id: 94, nome: "Cavalcade XL CTX" },
  { id: 95, nome: "Champion" },
  { id: 96, nome: "Cheburek" },
  { id: 97, nome: "Cheetah" },
  { id: 98, nome: "Cheetah Classic" },
  { id: 99, nome: "Chimera" },
  { id: 100, nome: "Chino" },
  { id: 101, nome: "Chino Custom" },
  { id: 102, nome: "Cinquemila" },
  { id: 103, nome: "Cliffhanger" },
  { id: 104, nome: "Clique" },
  { id: 105, nome: "Clique Wagon" },
  { id: 106, nome: "Club" },
  { id: 107, nome: "Cognoscenti" },
  { id: 108, nome: "Cognoscenti 55" },
  { id: 109, nome: "Cognoscenti Blindado" },
  { id: 110, nome: "Cognoscenti Cabrio" },
  { id: 111, nome: "Comet" },
  { id: 112, nome: "Comet Retro" },
  { id: 113, nome: "Comet S2" },
  { id: 114, nome: "Comet S2 Cabrio" },
  { id: 115, nome: "Comet S2 Cabrio CTX" },
  { id: 116, nome: "Comet S2 CTX" },
  { id: 117, nome: "Comet Safari" },
  { id: 118, nome: "Comet SR" },
  { id: 119, nome: "Contender" },
  { id: 120, nome: "Coquette" },
  { id: 121, nome: "Coquette BlackFin" },
  { id: 122, nome: "Coquette Classic" },
  { id: 123, nome: "Coquette D10" },
  { id: 124, nome: "Coquette Vice" },
  { id: 125, nome: "Coquette Vice Cabrio" },
  { id: 126, nome: "Corsita" },
  { id: 127, nome: "Cortador de grama" },
  { id: 128, nome: "Coyote" },
  { id: 129, nome: "Cruiser (Antiga)" },
  { id: 130, nome: "Cyclone" },
  { id: 131, nome: "Cypher" },
  { id: 132, nome: "Daemon Custom" },
  { id: 133, nome: "Dashound" },
  { id: 134, nome: "Declasse Dr1" },
  { id: 135, nome: "Defiler" },
  { id: 136, nome: "Deimos" },
  { id: 137, nome: "Deity" },
  { id: 138, nome: "Deluxo Retro" },
  { id: 139, nome: "Deveste" },
  { id: 140, nome: "Deviant" },
  { id: 141, nome: "Diablous" },
  { id: 142, nome: "Diablous Custom" },
  { id: 143, nome: "Dilettante" },
  { id: 144, nome: "Dominator" },
  { id: 145, nome: "Dominator ASP" },
  { id: 146, nome: "Dominator GTX" },
  { id: 147, nome: "Dominator Patrocinio" },
  { id: 148, nome: "Domitanor GTT" },
  { id: 149, nome: "Double T" },
  { id: 150, nome: "Draugur" },
  { id: 151, nome: "Drift Tampa" },
  { id: 152, nome: "Dubsta" },
  { id: 153, nome: "Dubsta 22" },
  { id: 154, nome: "Dubsta 6X6" },
  { id: 155, nome: "Dubsta II" },
  { id: 156, nome: "Dukes" },
  { id: 157, nome: "Dukes Beater" },
  { id: 158, nome: "Dyna King" },
  { id: 159, nome: "Dynasty" },
  { id: 160, nome: "Elegy Retro" },
  { id: 161, nome: "Elegy RH5" },
  { id: 162, nome: "Elegy RH6" },
  { id: 163, nome: "Elegy RH7" },
  { id: 164, nome: "Elegy RH8" },
  { id: 165, nome: "Elegy RH8 CTX" },
  { id: 166, nome: "Elegy RH9" },
  { id: 167, nome: "Elegy RHX" },
  { id: 168, nome: "Ellie" },
  { id: 169, nome: "Emerus" },
  { id: 170, nome: "Emperor" },
  { id: 171, nome: "Empilhadeira" },
  { id: 172, nome: "Endurex (Triathlon)" },
  { id: 173, nome: "Enduro" },
  { id: 174, nome: "Entity MT" },
  { id: 175, nome: "Entity XF" },
  { id: 176, nome: "Entity XXR" },
  { id: 177, nome: "Escavadeira" },
  { id: 178, nome: "Esperta" },
  { id: 179, nome: "Esskey" },
  { id: 180, nome: "ETR1" },
  { id: 181, nome: "Eudora" },
  { id: 182, nome: "Eudora Custom" },
  { id: 183, nome: "Euros" },
  { id: 184, nome: "Euros Classic" },
  { id: 185, nome: "Everon" },
  { id: 186, nome: "Exemplar" },
  { id: 187, nome: "F340 R" },
  { id: 188, nome: "F440 R" },
  { id: 189, nome: "F620" },
  { id: 190, nome: "Faction" },
  { id: 191, nome: "Faction Custom" },
  { id: 192, nome: "Faction Custom Donk" },
  { id: 193, nome: "Fagaloa" },
  { id: 194, nome: "Faggio" },
  { id: 195, nome: "Faggio Modified" },
  { id: 196, nome: "Faggio Sport" },
  { id: 197, nome: "FatBoy" },
  { id: 198, nome: "FatBoy 21" },
  { id: 199, nome: "FCR 1000" },
  { id: 200, nome: "FCR 1000 Custom" },
  { id: 201, nome: "Felon" },
  { id: 202, nome: "Felon GT" },
  { id: 203, nome: "Feltzer" },
  { id: 204, nome: "Fieldmaster" },
  { id: 205, nome: "Fixter (Corrida)" },
  { id: 206, nome: "Flash GT" },
  { id: 207, nome: "FMJ" },
  { id: 208, nome: "Food Truck" },
  { id: 209, nome: "FQ 2" },
  { id: 210, nome: "Fränken Stange" },
  { id: 211, nome: "Fugitive" },
  { id: 212, nome: "Furia" },
  { id: 213, nome: "Furore GT" },
  { id: 214, nome: "Furzen" },
  { id: 215, nome: "Fusilade" },
  { id: 216, nome: "Futo" },
  { id: 217, nome: "Futo GTX" },
  { id: 218, nome: "Gang Burrito" },
  { id: 219, nome: "Gargoyle" },
  { id: 220, nome: "Gauntlet" },
  { id: 221, nome: "Gauntlet Classic" },
  { id: 222, nome: "Gauntlet Classic Custom" },
  { id: 223, nome: "Gauntlet Hellfire" },
  { id: 224, nome: "Gauntlet S" },
  { id: 225, nome: "Gauntlet Turbo" },
  { id: 226, nome: "GB 200" },
  { id: 227, nome: "Glendale" },
  { id: 228, nome: "Glendale Custom" },
  { id: 229, nome: "GP1" },
  { id: 230, nome: "Granger" },
  { id: 231, nome: "Granger 3600LX" },
  { id: 232, nome: "Greenwood" },
  { id: 233, nome: "Gresley" },
  { id: 234, nome: "Growler" },
  { id: 235, nome: "GT 500" },
  { id: 236, nome: "Guardian" },
  { id: 237, nome: "Habanero" },
  { id: 238, nome: "Hakuchou" },
  { id: 239, nome: "Hakuchou Drag" },
  { id: 240, nome: "Hauler" },
  { id: 241, nome: "Hellion" },
  { id: 242, nome: "Hermes" },
  { id: 243, nome: "Hexer" },
  { id: 244, nome: "Hotknife" },
  { id: 245, nome: "Hotring" },
  { id: 246, nome: "Hotring Everon" },
  { id: 247, nome: "Hotring Hellfire" },
  { id: 248, nome: "Huntley S" },
  { id: 249, nome: "Hustler" },
  { id: 250, nome: "I-Wagen" },
  { id: 251, nome: "Ignus" },
  { id: 252, nome: "Imorgon" },
  { id: 253, nome: "Impaler" },
  { id: 254, nome: "Inductor" },
  { id: 255, nome: "Infernus" },
  { id: 256, nome: "Infernus Classic" },
  { id: 257, nome: "Ingot" },
  { id: 258, nome: "Innovation" },
  { id: 259, nome: "Intruder" },
  { id: 260, nome: "Issi" },
  { id: 261, nome: "Issi Classic" },
  { id: 262, nome: "Issi Rally" },
  { id: 263, nome: "Issi Sport" },
  { id: 264, nome: "Itali GTB" },
  { id: 265, nome: "Itali GTB Custom" },
  { id: 266, nome: "Itali GTO" },
  { id: 267, nome: "Itali GTO Stinger TT" },
  { id: 268, nome: "Itali RSX" },
  { id: 269, nome: "Jackal" },
  { id: 270, nome: "JB 700" },
  { id: 271, nome: "Jester" },
  { id: 272, nome: "Jester Classic" },
  { id: 273, nome: "Jester Custom" },
  { id: 274, nome: "Jester Patrocinio" },
  { id: 275, nome: "Jester RR" },
  { id: 276, nome: "Journey II" },
  { id: 277, nome: "Jubilee" },
  { id: 278, nome: "Jugular" },
  { id: 279, nome: "Junk Energy Inductor" },
  { id: 280, nome: "Kalahari" },
  { id: 281, nome: "Kamacho" },
  { id: 282, nome: "Kampfer" },
  { id: 283, nome: "Kanjo SJ" },
  { id: 284, nome: "Kawaii" },
  { id: 285, nome: "Khamelion" },
  { id: 286, nome: "Komoda" },
  { id: 287, nome: "Krieger" },
  { id: 288, nome: "Kuruma" },
  { id: 289, nome: "La Coureuse" },
  { id: 290, nome: "Landstalker" },
  { id: 291, nome: "Landstalker XL" },
  { id: 292, nome: "Lectro" },
  { id: 293, nome: "Liberator" },
  { id: 294, nome: "LM87" },
  { id: 295, nome: "Locust" },
  { id: 296, nome: "Lost Slamvan" },
  { id: 297, nome: "Lynx" },
  { id: 298, nome: "Mamba" },
  { id: 299, nome: "Manana" },
  { id: 300, nome: "Manana Custom" },
  { id: 301, nome: "Manchez" },
  { id: 302, nome: "Manchez Scout" },
  { id: 303, nome: "Manchez Scout C" },
  { id: 304, nome: "Marshall" },
  { id: 305, nome: "Massacro" },
  { id: 306, nome: "Massacro Patrocinio" },
  { id: 307, nome: "Mesa" },
  { id: 308, nome: "Mesa Offroad" },
  { id: 309, nome: "Michelli" },
  { id: 310, nome: "Minivan" },
  { id: 311, nome: "Minivan Custom" },
  { id: 312, nome: "Monroe" },
  { id: 313, nome: "MonstroCiti" },
  { id: 314, nome: "Moonbeam" },
  { id: 315, nome: "Moonbeam Custom" },
  { id: 316, nome: "Mule" },
  { id: 317, nome: "Mule Custom" },
  { id: 318, nome: "Mule Heist" },
  { id: 319, nome: "Mule Ramp-Door" },
  { id: 320, nome: "Nebula" },
  { id: 321, nome: "Nemesis" },
  { id: 322, nome: "Neo" },
  { id: 323, nome: "Neon" },
  { id: 324, nome: "Nero" },
  { id: 325, nome: "Nero Custom" },
  { id: 326, nome: "Nexus" },
  { id: 327, nome: "Nightblade" },
  { id: 328, nome: "Nightblade Classic" },
  { id: 329, nome: "Nightshade" },
  { id: 330, nome: "Novak" },
  { id: 331, nome: "Ocelot R88" },
  { id: 332, nome: "Omnis" },
  { id: 333, nome: "Omnis e-GT" },
  { id: 334, nome: "Ônibus" },
  { id: 335, nome: "Ônibus do Aeroporto" },
  { id: 336, nome: "Oracle" },
  { id: 337, nome: "Oracle XS" },
  { id: 338, nome: "Osiris" },
  { id: 339, nome: "Outlaw" },
  { id: 340, nome: "Packer" },
  { id: 341, nome: "Panthere" },
  { id: 342, nome: "Panto" },
  { id: 343, nome: "Paradise" },
  { id: 344, nome: "Paragon R" },
  { id: 345, nome: "Paragon R Blindado" },
  { id: 346, nome: "Pariah" },
  { id: 347, nome: "Patriot" },
  { id: 348, nome: "Patriot Mil-Spec" },
  { id: 349, nome: "Patriot Stretch" },
  { id: 350, nome: "PCJ 600" },
  { id: 351, nome: "Penetrator" },
  { id: 352, nome: "Penumbra" },
  { id: 353, nome: "Penumbra FF" },
  { id: 354, nome: "Penumbra Retro" },
  { id: 355, nome: "Penumbra Retro Cabrio" },
  { id: 356, nome: "Penumbra Retro Widebody" },
  { id: 357, nome: "Penumbra Retro Widebody Cabrio" },
  { id: 358, nome: "Peyote" },
  { id: 359, nome: "Peyote Custom" },
  { id: 360, nome: "Peyote Gasser" },
  { id: 361, nome: "Phantom" },
  { id: 362, nome: "Phantom Custom" },
  { id: 363, nome: "Phoenix" },
  { id: 364, nome: "Picador" },
  { id: 365, nome: "Pigalle" },
  { id: 366, nome: "Pony" },
  { id: 367, nome: "Pororoca" },
  { id: 368, nome: "Postlude" },
  { id: 369, nome: "Pounder" },
  { id: 370, nome: "Powersurge" },
  { id: 371, nome: "Prairie" },
  { id: 372, nome: "Premier" },
  { id: 373, nome: "Previon" },
  { id: 374, nome: "Primo" },
  { id: 375, nome: "Primo Custom" },
  { id: 376, nome: "Progen Pr4" },
  { id: 377, nome: "Radius" },
  { id: 378, nome: "Raiden" },
  { id: 379, nome: "Rallytruck" },
  { id: 380, nome: "Rampant Rocket" },
  { id: 381, nome: "Rancher XL" },
  { id: 382, nome: "Rapid GT" },
  { id: 383, nome: "Rapid GT Cabrio" },
  { id: 384, nome: "Rapid GT3" },
  { id: 385, nome: "Raptor" },
  { id: 386, nome: "Rat-Truck" },
  { id: 387, nome: "Ratel" },
  { id: 388, nome: "RE-7B" },
  { id: 389, nome: "Reaper" },
  { id: 390, nome: "Rebel" },
  { id: 391, nome: "Rebla GTS" },
  { id: 392, nome: "Redwood Gauntlet" },
  { id: 393, nome: "Reever" },
  { id: 394, nome: "Regina" },
  { id: 395, nome: "Remus" },
  { id: 396, nome: "Remus II" },
  { id: 397, nome: "Retinue" },
  { id: 398, nome: "Retinue MK II" },
  { id: 399, nome: "Revolter" },
  { id: 400, nome: "Rhapsody" },
  { id: 401, nome: "Rhinehart" },
  { id: 402, nome: "Rhinehart M" },
  { id: 403, nome: "Riata" },
  { id: 404, nome: "Riata TX" },
  { id: 405, nome: "Rocoto" },
  { id: 406, nome: "Roosevelt" },
  { id: 407, nome: "Roosevelt Valor" },
  { id: 408, nome: "Roxanne" },
  { id: 409, nome: "RT3000" },
  { id: 410, nome: "Ruffian" },
  { id: 411, nome: "Ruiner" },
  { id: 412, nome: "Ruiner ZZ-8" },
  { id: 413, nome: "Rumpo Off-road" },
  { id: 414, nome: "Ruston" },
  { id: 415, nome: "S230" },
  { id: 416, nome: "S80RR" },
  { id: 417, nome: "S95 CTX" },
  { id: 418, nome: "Sabre Turbo" },
  { id: 419, nome: "Sabre Turbo Custom" },
  { id: 420, nome: "Sadler" },
  { id: 421, nome: "Sanchez" },
  { id: 422, nome: "Sanchez Patrocínio" },
  { id: 423, nome: "Sanctus" },
  { id: 424, nome: "Sandking" },
  { id: 425, nome: "Sandking XL" },
  { id: 426, nome: "Savestra" },
  { id: 427, nome: "SC1" },
  { id: 428, nome: "Schafter" },
  { id: 429, nome: "Schafter LWB" },
  { id: 430, nome: "Schafter V12" },
  { id: 431, nome: "Schafter V12 (Blindado)" },
  { id: 432, nome: "Schlagen GT" },
  { id: 433, nome: "Schneider STR" },
  { id: 434, nome: "Schwartzer" },
  { id: 435, nome: "Scorcher (Trilha)" },
  { id: 436, nome: "Scrap Truck" },
  { id: 437, nome: "Seminole" },
  { id: 438, nome: "Seminole Frontier" },
  { id: 439, nome: "Sentinel" },
  { id: 440, nome: "Sentinel Classic" },
  { id: 441, nome: "Sentinel Classic Widebody" },
  { id: 442, nome: "Sentinel SG4" },
  { id: 443, nome: "Sentinel XS" },
  { id: 444, nome: "Serrano" },
  { id: 445, nome: "Seven 70" },
  { id: 446, nome: "Sheava S" },
  { id: 447, nome: "Slamtruck" },
  { id: 448, nome: "Slamvan" },
  { id: 449, nome: "Slamvan Custom" },
  { id: 450, nome: "Slave" },
  { id: 451, nome: "SM722" },
  { id: 452, nome: "Sovereign" },
  { id: 453, nome: "Specter" },
  { id: 454, nome: "Specter Custom" },
  { id: 455, nome: "Speedo" },
  { id: 456, nome: "Speedo Express" },
  { id: 457, nome: "Stafford" },
  { id: 458, nome: "Stallion" },
  { id: 459, nome: "Stanier" },
  { id: 460, nome: "Stinger" },
  { id: 461, nome: "Stinger GT" },
  { id: 462, nome: "Stirling GT" },
  { id: 463, nome: "Stratum" },
  { id: 464, nome: "Street Blazer" },
  { id: 465, nome: "Streiter" },
  { id: 466, nome: "Stretch" },
  { id: 467, nome: "Stryder" },
  { id: 468, nome: "Sugoi" },
  { id: 469, nome: "Sultan" },
  { id: 470, nome: "Sultan Classic" },
  { id: 471, nome: "Sultan RS" },
  { id: 472, nome: "Sultan RS Classic" },
  { id: 473, nome: "Sultan RSX" },
  { id: 474, nome: "Sunrise R" },
  { id: 475, nome: "Super Diamond" },
  { id: 476, nome: "Surano" },
  { id: 477, nome: "Surfer" },
  { id: 478, nome: "Surfer Custom" },
  { id: 479, nome: "Surge" },
  { id: 480, nome: "Swinger" },
  { id: 481, nome: "T20" },
  { id: 482, nome: "Tahoma Coupe" },
  { id: 483, nome: "Tailgater" },
  { id: 484, nome: "Tailgater S" },
  { id: 485, nome: "Taipan" },
  { id: 486, nome: "Tampa" },
  { id: 487, nome: "Tempesta" },
  { id: 488, nome: "Tempesta Custom" },
  { id: 489, nome: "Templar" },
  { id: 490, nome: "TerrorByte" },
  { id: 491, nome: "Tezeract" },
  { id: 492, nome: "The Lost Daemon" },
  { id: 493, nome: "Thrax" },
  { id: 494, nome: "Thrust" },
  { id: 495, nome: "Tigon" },
  { id: 496, nome: "Tipper" },
  { id: 497, nome: "Tipper 2" },
  { id: 498, nome: "Titan" },
  { id: 499, nome: "Titan Low" },
  { id: 500, nome: "Titan T" },
  { id: 501, nome: "Torero" },
  { id: 502, nome: "Torero XO" },
  { id: 503, nome: "Tornado" },
  { id: 504, nome: "Tornado Custom" },
  { id: 505, nome: "Tornado Soft Top" },
  { id: 506, nome: "Toros" },
  { id: 507, nome: "Tour Bus" },
  { id: 508, nome: "Trash Truck" },
  { id: 509, nome: "Tri-cycles (Triathlon)" },
  { id: 510, nome: "Trophy Truck" },
  { id: 511, nome: "Trophy Truck Limited" },
  { id: 512, nome: "Tropos" },
  { id: 513, nome: "Tulip" },
  { id: 514, nome: "Tulip M100" },
  { id: 515, nome: "Turismo" },
  { id: 516, nome: "Turismo Classic" },
  { id: 517, nome: "Turismo S" },
  { id: 518, nome: "Tyrant" },
  { id: 519, nome: "Tyrus" },
  { id: 520, nome: "Utility Truck" },
  { id: 521, nome: "Utility Truck Contender" },
  { id: 522, nome: "V-STR" },
  { id: 523, nome: "Vacca" },
  { id: 524, nome: "Vader" },
  { id: 525, nome: "Vagner" },
  { id: 526, nome: "Vagrant" },
  { id: 527, nome: "Vamos" },
  { id: 528, nome: "Vectre" },
  { id: 529, nome: "Velox" },
  { id: 530, nome: "Verlierer" },
  { id: 531, nome: "Verus" },
  { id: 532, nome: "Vigero" },
  { id: 533, nome: "Vigero Rumbler" },
  { id: 534, nome: "Vigero VL1" },
  { id: 535, nome: "Vigero ZX" },
  { id: 536, nome: "Vindicator" },
  { id: 537, nome: "Virgo" },
  { id: 538, nome: "Virgo Classic" },
  { id: 539, nome: "Virgo Classic Custom" },
  { id: 540, nome: "Virtue" },
  { id: 541, nome: "Viseris" },
  { id: 542, nome: "Visione" },
  { id: 543, nome: "Voltic" },
  { id: 544, nome: "Voodoo Custom" },
  { id: 545, nome: "Vortex" },
  { id: 546, nome: "Vulture" },
  { id: 547, nome: "Walton L35" },
  { id: 548, nome: "Warrener" },
  { id: 49, nome: "Warrener HKR" },
  { id: 550, nome: "Washington" },
  { id: 551, nome: "Weevil" },
  { id: 552, nome: "Weevil Custom" },
  { id: 553, nome: "Whippet (Triathlon)" },
  { id: 554, nome: "Windsor" },
  { id: 555, nome: "Windsor Drop" },
  { id: 556, nome: "Winky" },
  { id: 557, nome: "Wintergreen" },
  { id: 558, nome: "Wolfsbane" },
  { id: 559, nome: "X80 Prototype" },
  { id: 560, nome: "XA-21" },
  { id: 561, nome: "XLS" },
  { id: 562, nome: "XLS Blindada" },
  { id: 563, nome: "Yosemite" },
  { id: 564, nome: "Yosemite Drift" },
  { id: 565, nome: "Yosemite Rancher" },
  { id: 566, nome: "Youga" },
  { id: 567, nome: "Youga Classic" },
  { id: 568, nome: "Youga Classic 4x4" },
  { id: 569, nome: "Z 190" },
  { id: 570, nome: "Z-Type" },
  { id: 571, nome: "Zeno" },
  { id: 572, nome: "Zentorno" },
  { id: 573, nome: "Zion" },
  { id: 574, nome: "Zion Cabrio" },
  { id: 575, nome: "Zion Classic" },
  { id: 576, nome: "Zion Classic CTX" },
  { id: 577, nome: "Zombie Bobber" },
  { id: 578, nome: "Zombie Chopper" },
  { id: 579, nome: "Zorrusso" },
  { id: 580, nome: "ZR Classic" },
  { id: 581, nome: "ZR-380 S" },
  { id: 582, nome: "ZR-390" },
  { id: 583, nome: "ZR250" },
  { id: 584, nome: "ZR350" },
  { id: 585, nome: "ZR350 Custom" },
];
export const escapeOptions = [
  { id: 2, label: "I4 Atual BF (Golf GTI*)" },
  { id: 3, label: "I4 Atual Karin (Sultan)" },
  { id: 4, label: "I4 Atual Karin (Kuruma)" },
  { id: 5, label: "I4 Antigo Annis" },
  { id: 6, label: "I4 Antigo Maibatsu (Sunrise)" },
  { id: 7, label: "I4 Antigo Maibatsu (Sunrise Tuned)" },
  { id: 8, label: "I4 Antigo Dinka (RT3000)" },
  { id: 9, label: "I4 Antigo Dinka (Type R*)" },
  { id: 10, label: "I4 Antigo Karin (Futo)" },
  { id: 11, label: "I5 Atual Obey (TT RS/RS3*)" },
  { id: 12, label: "I5 Antigo Obey (Omnis)" },
  { id: 13, label: "I6 Atual Dinka (Jester RR)" },
  { id: 14, label: "I6 Atual Übermacht (Cypher)" },
  { id: 15, label: "I6 Atual Übermacht (M4*)" },
  { id: 16, label: "I6 Antigo Dinka (Jester Classic)" },
  { id: 17, label: "I6 Antigo Dinka (Jester Classic Tuned)" },
  { id: 18, label: "I6 Antigo Annis (Elegy RH7)" },
  { id: 19, label: "I6 Antigo Karin (Motor 1J*)" },
  { id: 20, label: "I6 Antigo Annis (Elegy RH5/RH7)" },
  { id: 21, label: "I6 Antigo Übermacht (Sentinel SG4)" },
  { id: 22, label: "I6 Antigo Dinka (Nexus)" },
  { id: 23, label: "I6 Antigo Karin (190Z)" },
  { id: 24, label: "I6 Antigo Bravado Diesel (RAM*)" },
  { id: 25, label: "I6 Antigo Annis (Hellion)" },
  { id: 26, label: "V6 Atual Annis (Elegy GT)" },
  { id: 27, label: "V6 Atual Annis (ZR380 Stroke)" },
  { id: 28, label: "V6 Atual Annis (ZR380)" },
  { id: 29, label: "V6 Atual Lampadati (Komoda)" },
  { id: 30, label: "V6 Atual Obey (Tailgater S)" },
  { id: 31, label: "V6 Atual Vapid (FMJ)" },
  { id: 32, label: "V8 Atual Obey" },
  { id: 33, label: "V8 Atual Übermacht (M5*)" },
  { id: 34, label: "V8 Atual Declasse (Vigero ZX)" },
  { id: 35, label: "V8 Atual Bravado (Buffalo STX)" },
  { id: 36, label: "V8 Atual Grotti (Itali RSX)" },
  { id: 37, label: "V8 Atual Bravado (Gauntlet)" },
  { id: 38, label: "V8 Atual Benefactor (Schafter)" },
  { id: 39, label: "V8 Atual Invetero (Coquette)" },
  { id: 40, label: "V8 Atual Vapid (Dominator GTX/GT)" },
  { id: 41, label: "V8 Atual Vapid (Dominator Veneno)" },
  { id: 42, label: "V8 Atual Progen (T20)" },
  { id: 43, label: "V8 Atual Progen (Aurora)" },
  { id: 44, label: "V8 Atual Pfister (811)" },
  { id: 45, label: "V8 Atual Übermacht (Sentinel)" },
  { id: 46, label: "V8 Atual Obey (Rocoto)" },
  { id: 47, label: "V8 Atual Vapid (Caracara)" },
  { id: 48, label: "V8 Antigo Benefactor (Schwartzer/Dubsta)" },
  { id: 49, label: "V8 Antigo LS Swap" },
  { id: 50, label: "V8 Antigo Übermacht (Sentinel)" },
  { id: 51, label: "V8 Antigo Imponte (Dukes)" },
  { id: 52, label: "V8 Antigo Grotti (348*)" },
  { id: 53, label: "V8 Antigo Declasse (Vigero VL1)" },
  { id: 54, label: "V8 Antigo Hot Rod" },
  { id: 55, label: "V8 Antigo Crown Vic" },
  { id: 56, label: "V10 Atual Obey (9F)" },
  { id: 57, label: "V10 Atual Bravado (Banshee)" },
  { id: 58, label: "V10 Atual Pegassi (Tempesta)" },
  { id: 59, label: "V10 Atual Pfister (Carrera GT*)" },
  { id: 60, label: "V10 Atual Übermacht (M6*)" },
  { id: 61, label: "V10 Antigo Pegassi (Vacca)" },
  { id: 62, label: "V12 Atual Pegassi (Osiris)" },
  { id: 63, label: "V12 Atual Pegassi (Zentorno)" },
  { id: 64, label: "V12 Atual Dewbauchee (Massacro)" },
  { id: 65, label: "V12 Atual Pegassi (Osiris)" },
  { id: 66, label: "V12 Atual Pegassi (Zentorno)" },
  { id: 67, label: "V12 Atual Grotti (Turismo R)" },
  { id: 68, label: "V12 Antigo Grotti (F50*)" },
  { id: 69, label: "V12 Antigo Grotti (Cheetah)" },
  { id: 70, label: "V12 Antigo Progen (GP1)" },
  { id: 71, label: "V12 Antigo Grotti (Cheetah Classic)" },
  { id: 72, label: "F4 Atual Pfister (Growler)" },
  { id: 73, label: "F4 Atual Karin (Sultan)" },
  { id: 74, label: "F4 Antigo Karin (Sultan)" },
  { id: 75, label: "F6 Atual Pfister (Comet S2 Tuned)" },
  { id: 76, label: "F6 Atual Pfister (Comet S2)" },
  { id: 77, label: "F6 Antigo Pfister (Comet Retro)" },
  { id: 78, label: "W16 Antigo Truffade" },
  { id: 79, label: "Rotatório Atual Annis" },
  { id: 80, label: "Rotatório Antigo Annis (ZR350)" },
];
